version: '1.0'

services:

  db:
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    environment:
      POSTGRES_USER: "${DB_USER:?err}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:?err}"
    restart: always
    networks:
      - platform
    volumes:
      - db-data:/var/lib/postgresql/data:delegated

  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 80:8080
    environment:
      CMS_ADMIN_USERNAME: "${CMS_ADMIN_USERNAME:?err}"
      CMS_ADMIN_PASSWORD: "${CMS_ADMIN_PASSWORD:?err}"
      CMS_FORCE_SSL: "${CMS_FORCE_SSL:-true}"
      DB_SERVER_NAME: "db"
      DB_SSL: "${DB_SSL:-false}"
      DB_USER: "${DB_USER:?err}"
      DB_PASSWORD: "${DB_PASSWORD:?err}"
      DB_NAME: "${DB_NAME:-simis-cms}"
    restart: on-failure
    depends_on:
      - db
    networks:
      - platform
    volumes:
      - web-data:/opt/simis:delegated
  
volumes:
  db-data:
  web-data:

networks:
  platform:
